master.host=localhost
master.port=5001

worker.count=3
worker.0.host=localhost
worker.1.host=localhost
worker.2.host=localhost
worker.port=6001

reducer.host=localhost
reducer.port=7001

srg.host=localhost
srg.port=8001