master.host=10.26.21.182
master.port=5001

worker.count=3
worker.0.host=localhost
worker.1.host=10.26.25.38
worker.2.host=10.26.21.182
worker.port=6001

reducer.host=localhost
reducer.port=7001

srg.host=10.26.25.38
srg.port=8001