master.host=localhost
master.port=5001

worker.count=3
worker.0=localhost:6001
worker.1=localhost:6002
worker.2=localhost:6003

reducer.host=localhost
reducer.port=7001

srg.host=localhost
srg.port=8001